runtime: nodejs20

env_variables:
  GOOGLE_CLOUD_PROJECT: clickthemovingdot

automatic_scaling:
  min_instances: 1
  max_instances: 100
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# Security: Force HTTPS and add security headers
handlers:
- url: /.*
  script: auto
  secure: always
  
# Additional security settings
network:
  forwarded_ports: []  # No additional ports needed
